package org.mythogyan.intent;

public enum Intent {
    GET_CHARACTER_INFO,
    GET_AVATARS_OF_DEITY,
    GET_CONSORTS_OF_CHARACTER,
    GET_TEACHER_OF_CHARACTER,
    GET_PARENTS_OF_CHARACTER,
    GET_CHILDREN_OF_CHARACTER,
    GET_CONCEPTS_OF_CHARACTER,
    GET_CONNECTION_BETWEEN_CHARACTERS,
    UNKNOWN
}
